### ISSUE TITLE
During Script Altercation the follow error occurs

### ISSUE THREAD

**Issue by DepewTechnologies** [ben-roberts/uMMORPG-Network-Zones#4]
When the following code is added to NetworkManagerMMO.cs

`

// Auto Select Character Flow - Skip Character Selection Screen
 if (NetworkZone.Instance != null && !string.IsNullOrEmpty(NetworkZone.Instance.autoSelectCharacter))
 {
 	// cache and clear auto select
 	var selectCharacter = NetworkZone.Instance.autoSelectCharacter;
 	NetworkZone.Instance.ClearSelectCharacter();

 	int index = message.characters.ToList().FindIndex(c => c.name == selectCharacter);
 	if (index != -1)
 	{
 		state = NetworkState.World;

 		// clear previous previews in any case
 		ClearPreviews();

 		// Add the player
 		print("[Zones]: autoselect " + selectCharacter + "(" + index + ")");
 		byte[] extra = BitConverter.GetBytes(index);
 		ClientScene.AddPlayer(NetworkClient.connection, extra);

 		// send CharacterSelect message (need to be ready first!)
 		NetworkClient.connection.Send(new CharacterSelectMsg(index));

 		return;
 	}
 }
 // rest of the original code  in NetworkManagerMMO.OnClientCharactersAvailable goes below here

`

Error One:

Assets\uMMORPG\Scripts\NetworkManagerMMO.cs(294,36): error CS1061: 'CharactersAvailableMsg.CharacterPreview[]' does not contain a definition for 'ToList' and no accessible extension method 'ToList' accepting a first argument of type 'CharactersAvailableMsg.CharacterPreview[]' could be found (are you missing a using directive or an assembly reference?)

Error Two:

Assets\uMMORPG\Scripts\NetworkManagerMMO.cs(307,38): error CS1729: 'CharacterSelectMsg' does not contain a constructor that takes 1 arguments

**Comment by Zurigan** [comment]
1. `using System.Linq;` is needed for ToList() ... if you use a code editor like Rider it can often work this stuff out for you, saves a lot of head-scratching!

2. Looks like that line is `NetworkClient.connection.Send(new CharacterSelectMsg{index =  index});` in my actual code, please try that, I've updated the readme, thanks for pointing it out.

**Comment by DepewTechnologies** [comment]
Thank you for the response :)
